---
abstract: 'check coderefs for unintended lexical capture'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  Capture::Tiny: 0
  Test::Fatal: 0
  Test::More: 0.98
  Test::Refcount: 0.07
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Closure-Explicit
requires:
  PadWalker: 0
  parent: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Closure-Explicit
  homepage: http://search.cpan.org/dist/Closure-Explicit/
version: 0.001
